CREATE TABLE IF NOT EXISTS automation_tasks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_no VARCHAR(64) NOT NULL,
  task_type VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  channel VARCHAR(64) NOT NULL DEFAULT '',
  stage_name VARCHAR(64) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL,
  source_type VARCHAR(64) NOT NULL DEFAULT '',
  source_id BIGINT NULL,
  customer_id BIGINT NULL,
  customer_name VARCHAR(128) NOT NULL DEFAULT '',
  product_name VARCHAR(128) NOT NULL DEFAULT '',
  order_id BIGINT NULL,
  invoice_id BIGINT NULL,
  service_id BIGINT NULL,
  service_no VARCHAR(64) NOT NULL DEFAULT '',
  provider_type VARCHAR(64) NOT NULL DEFAULT '',
  provider_resource_id VARCHAR(128) NOT NULL DEFAULT '',
  action_name VARCHAR(64) NOT NULL DEFAULT '',
  operator_type VARCHAR(32) NOT NULL DEFAULT '',
  operator_name VARCHAR(128) NOT NULL DEFAULT '',
  request_payload LONGTEXT NULL,
  result_payload LONGTEXT NULL,
  message VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_automation_tasks_task_no (task_no),
  KEY idx_automation_tasks_status (status),
  KEY idx_automation_tasks_task_type (task_type),
  KEY idx_automation_tasks_channel (channel),
  KEY idx_automation_tasks_service_id (service_id),
  KEY idx_automation_tasks_created_at (created_at)
);
