CREATE TABLE IF NOT EXISTS order_requests (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  request_no VARCHAR(64) NOT NULL UNIQUE,
  order_id BIGINT NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  customer_id BIGINT NOT NULL,
  customer_name VARCHAR(128) NOT NULL,
  product_name VARCHAR(191) NOT NULL,
  type VARCHAR(32) NOT NULL DEFAULT 'RENEW',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  summary VARCHAR(191) NOT NULL DEFAULT '',
  reason TEXT NOT NULL,
  current_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  requested_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  current_billing_cycle VARCHAR(32) NOT NULL DEFAULT '',
  requested_billing_cycle VARCHAR(32) NOT NULL DEFAULT '',
  source_type VARCHAR(32) NOT NULL DEFAULT 'ADMIN',
  source_id BIGINT NULL,
  source_name VARCHAR(128) NOT NULL DEFAULT '',
  processor_type VARCHAR(32) NOT NULL DEFAULT '',
  processor_id BIGINT NULL,
  processor_name VARCHAR(128) NOT NULL DEFAULT '',
  process_note TEXT NULL,
  payload_json JSON NULL,
  processed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_order_requests_order_created (order_id, created_at),
  KEY idx_order_requests_customer_created (customer_id, created_at),
  KEY idx_order_requests_status_created (status, created_at),
  KEY idx_order_requests_type_created (type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
