param(
  [string]$OutputRoot = "output\release\windows-amd64",
  [string]$PackageName = "wuqiongyun-idc",
  [switch]$SkipBuild,
  [switch]$SkipZip
)

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
$releaseRoot = Join-Path $projectRoot $OutputRoot
$packageRoot = Join-Path $releaseRoot $PackageName
$adminDist = Join-Path $projectRoot "apps\admin-web\dist"
$portalDist = Join-Path $projectRoot "apps\portal-web\dist"
$databaseRoot = Join-Path $packageRoot "database"
$adminWebRoot = Join-Path $packageRoot "web\admin"
$portalWebRoot = Join-Path $packageRoot "web\portal"
$apiBinary = Join-Path $packageRoot "wuqiongyun-idc-api.exe"
$zipPath = Join-Path $releaseRoot ($PackageName + ".zip")

function Write-Utf8File {
  param(
    [string]$Path,
    [string]$Content
  )

  $directory = Split-Path -Parent $Path
  if ($directory -and -not (Test-Path $directory)) {
    New-Item -ItemType Directory -Path $directory -Force | Out-Null
  }

  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

function Merge-SqlFiles {
  param(
    [string[]]$Files,
    [string]$Title
  )

  $builder = New-Object System.Text.StringBuilder
  [void]$builder.AppendLine("-- " + $Title)
  [void]$builder.AppendLine("-- Generated by scripts/build-release.ps1")
  [void]$builder.AppendLine("SET NAMES utf8mb4;")
  [void]$builder.AppendLine("SET FOREIGN_KEY_CHECKS = 0;")
  [void]$builder.AppendLine("")

  foreach ($file in $Files) {
    $content = [System.IO.File]::ReadAllText($file)
    [void]$builder.AppendLine("-- >>> " + [System.IO.Path]::GetFileName($file))
    [void]$builder.AppendLine($content.TrimEnd())
    [void]$builder.AppendLine("")
  }

  [void]$builder.AppendLine("SET FOREIGN_KEY_CHECKS = 1;")
  return $builder.ToString()
}

if (Test-Path $packageRoot) {
  Remove-Item $packageRoot -Recurse -Force
}

New-Item -ItemType Directory -Path $packageRoot -Force | Out-Null

if (-not $SkipBuild) {
  Push-Location $projectRoot
  try {
    npm run build:admin
    npm run build:portal
    go build -trimpath -o $apiBinary ./apps/api/cmd/server
  } finally {
    Pop-Location
  }
}

if (-not (Test-Path $adminDist)) {
  throw "Admin build output not found: $adminDist"
}

if (-not (Test-Path $portalDist)) {
  throw "Portal build output not found: $portalDist"
}

if (-not (Test-Path $apiBinary)) {
  throw "API binary not found: $apiBinary"
}

New-Item -ItemType Directory -Path $adminWebRoot -Force | Out-Null
New-Item -ItemType Directory -Path $portalWebRoot -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $databaseRoot "migrations\mysql") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $databaseRoot "seed\mysql") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $packageRoot "docs") -Force | Out-Null

Copy-Item -Path (Join-Path $adminDist "*") -Destination $adminWebRoot -Recurse -Force
Copy-Item -Path (Join-Path $portalDist "*") -Destination $portalWebRoot -Recurse -Force
Copy-Item -Path (Join-Path $projectRoot ".env.example") -Destination (Join-Path $packageRoot ".env.example") -Force
Copy-Item -Path (Join-Path $projectRoot "docs\RELEASE.md") -Destination (Join-Path $packageRoot "README.md") -Force
Copy-Item -Path (Join-Path $projectRoot "docs\*.md") -Destination (Join-Path $packageRoot "docs") -Force
Copy-Item -Path (Join-Path $projectRoot "migrations\mysql\*.sql") -Destination (Join-Path $databaseRoot "migrations\mysql") -Force
Copy-Item -Path (Join-Path $projectRoot "seed\mysql\*.sql") -Destination (Join-Path $databaseRoot "seed\mysql") -Force

$migrationFiles = Get-ChildItem -Path (Join-Path $projectRoot "migrations\mysql") -Filter "*.sql" | Sort-Object Name | Select-Object -ExpandProperty FullName
$seedFiles = Get-ChildItem -Path (Join-Path $projectRoot "seed\mysql") -Filter "*.sql" | Sort-Object Name | Select-Object -ExpandProperty FullName

Write-Utf8File -Path (Join-Path $databaseRoot "install-clean.sql") -Content (Merge-SqlFiles -Files $migrationFiles -Title "Wuqiongyun IDC clean install bundle")
Write-Utf8File -Path (Join-Path $databaseRoot "install-demo.sql") -Content (Merge-SqlFiles -Files ($migrationFiles + $seedFiles) -Title "Wuqiongyun IDC demo install bundle")

$startPs1 = @'
param(
  [string]$EnvFile = ".env.local"
)

$ErrorActionPreference = "Stop"
$packageRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $packageRoot

if (Test-Path $EnvFile) {
  Get-Content $EnvFile | ForEach-Object {
    $line = $_.Trim()
    if (-not $line -or $line.StartsWith("#")) {
      return
    }

    $parts = $line.Split("=", 2)
    if ($parts.Length -eq 2) {
      [System.Environment]::SetEnvironmentVariable($parts[0], $parts[1])
      Set-Item -Path ("Env:" + $parts[0]) -Value $parts[1]
    }
  }
}

$exe = Join-Path $packageRoot "wuqiongyun-idc-api.exe"
if (-not (Test-Path $exe)) {
  throw "API executable not found: $exe"
}

$listenAddr = if ($env:HTTP_ADDR) { $env:HTTP_ADDR } else { ":18080" }
$displayBase = if ($listenAddr.StartsWith(":")) { "http://127.0.0.1$listenAddr" } else { "http://$listenAddr" }

Write-Host ""
Write-Host "Wuqiongyun IDC suite started"
Write-Host "Admin URL:  $displayBase/admin/"
Write-Host "Portal URL: $displayBase/portal/"
Write-Host "Health URL: $displayBase/api/v1/health"
Write-Host ""

& $exe
exit $LASTEXITCODE
'@

$startBat = @'
@echo off
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0start.ps1"
'@

$releaseInfo = @"
{
  "name": "$PackageName",
  "builtAt": "$(Get-Date -Format "yyyy-MM-dd HH:mm:ss")",
  "apiBinary": "wuqiongyun-idc-api.exe",
  "adminEntry": "http://127.0.0.1:18080/admin/",
  "portalEntry": "http://127.0.0.1:18080/portal/",
  "health": "http://127.0.0.1:18080/api/v1/health"
}
"@

Write-Utf8File -Path (Join-Path $packageRoot "start.ps1") -Content $startPs1
Write-Utf8File -Path (Join-Path $packageRoot "start.bat") -Content $startBat
Write-Utf8File -Path (Join-Path $packageRoot "release-info.json") -Content $releaseInfo

if ((-not $SkipZip) -and (Test-Path $packageRoot)) {
  if (Test-Path $zipPath) {
    Remove-Item $zipPath -Force
  }
  Compress-Archive -Path $packageRoot -DestinationPath $zipPath -Force
}

Write-Host ""
Write-Host "Release ready:"
Write-Host "  Directory: $packageRoot"
if (-not $SkipZip) {
  Write-Host "  Zip:       $zipPath"
}
Write-Host ""
